### ISSUE TITLE
building returns error

### ISSUE THREAD

**Issue by willbasky** [spell-music/csound-catalog#3]
Resolver is `resolver: lts-11.6`
Extra-deps in yaml are:
```
extra-deps: 
- csound-expression-dynamic-0.3.2
- csound-expression-opcodes-0.0.4.0
- csound-expression-typed-0.2.1.0
- temporal-media-0.6.3
- data-fix-cse-0.0.2
- csound-expression-5.3.1
- csound-catalog-0.7.1
- csound-sampler-0.0.8.1
- sharc-timbre-0.2
```
in cabal:
```
  build-depends:      base >= 4.7 && < 5,
                               csound-expression
```
`stack install csound-catalog` returns me big list of errors
[error.log](https://github.com/spell-music/csound-catalog/files/1942610/error.log)

**Comment by anton-k** [comment]
try again, I've pused recent changes, list of errors is not so big, there are many warnings though

**Comment by willbasky** [comment]
Снова ошибки выходят, у или предупреждения. А версия так и осталась 0.7.1?
Errors and warning returned. Is it version 0.7.1 still?

**Comment by anton-k** [comment]
csound-expression-5.3.2, it's not released on hackage yet
csound-expression-typed-0.2.2.0

I'm planning to release soon. This week. Stay tuned!

**Comment by anton-k** [comment]
So if you want to use stack the right way would be to reference the github repos. 
I think I need to group them all in single repo and make stack-yaml for all of them

but not yet

**Comment by willbasky** [comment]
csound-expression installed well.
csound-catalog has problem only.

Ok.

**Comment by willbasky** [comment]
Yes, I use stack for all of required packages.

**Comment by willbasky** [comment]
Version 0.7.2 of csound-catalog has build successfully! 
Thanks!
